dbt_master:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: sudeepth
      pass: password
      dbname: dbt_masterDB
      schema: public

    # prod:
    #   type: postgres
    #   threads: [1 or more]
    #   host: [host]
    #   port: [port]
    #   user: [prod_username]
    #   pass: [prod_password]
    #   dbname: [dbname]
    #   schema: [prod_schema]

  target: dev
